AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

  # above two lines necessary to convert SAM template to CloudFormation template
Description: A SAM (Serverless Application Model) that uses a transforma & Cloudformation to creat api gateway, lamda function, and dynamo db table necessary to store a visitor counter.

Globals: # any parameters you want available to all your resources
    Function:
      Runtime: python3.6 # language used at runtime
      Timeout: 180 # timeout for a given lambda function execution
      Environment:
          Variables: # these will be important later
              DYNAMO_TABLE: !Ref dynamodb_resume_visitors_table
              DB_ENDPOINT: http://dynamodb.us-east-1.amazonaws.com
              REGION_NAME: us-east-1

Resources:

  #Lambda Functions https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  GetVisitorsFunction: # the resource’s logical name
      Type: AWS::Serverless::Function
      Properties:
          Handler: function.get_data_handler # the path to the lambda handler code
          Policies: AmazonDynamoDBFullAccess # default IAM policy that allows the lambda to read and write to our soon to be defined Dynamo instance
          Runtime: python3.8
          CodeUri:
            ZipFile: lambda_python_functions/lambda_read_and_increment.py
          Events:
              Api: # This lambda is triggered by a request to the API Gateway Endpoint /get-breed
                  Type: Api
                  Properties:
                      Path: /get-visitors
                      Method: get

  ResetVisitorTableFunction:
      Type: AWS::Serverless::Function
      Properties:
          Handler: function.clear_table_handler
          Policies: AmazonDynamoDBFullAccess
          Runtime: python3.8
          CodeUri:
            ZipFile: lambda_python_functions/lambda_clear.py
          Events:
            #  Timer:  you can configure a timer to delete at certain intervals
                  # Type: Schedule
                  # Properties:
                    #  Schedule: cron(0 4 * * ? *) # will run once a day at midnight
          Api: # Note: you can define multiple events that will trigger the lambda execution
              Type: Api
              Properties:
                  Path: /clear-table
                  Method: get

  #Defines the DynamDB table that the lambda functions above are expecting:
  dynamodb_resume_visitors_table:
      Type: AWS::Serverless::SimpleTable #or AWS::DynamoDB::Table as "This property is passed directly to the TableName property of an AWS::DynamoDB::Table resource.  - This property is passed directly to the TableName property of an AWS::DynamoDB::Table resource.
      Properties:
        TableName: dynamodb_resume_visitors_table
        PrimaryKey:
            Name: ip
            Type: String
        ProvisionedThroughput:
            ReadCapacityUnit: 5
            WriteCapacityUnits: 5
        Tags:
            AppType: Serverless

  #Dynamo DB table from https://seanjziegler.com/how-to-build-a-free-static-resume-site-with-aws-s3-cloudfront-and-route-53/#5-deploy-a-dynamodb-table-with-cloudformation
