AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

  # above two lines necessary to convert SAM template to CloudFormation template
Description: A SAM (Serverless Application Model) that uses a transforma & Cloudformation to creat api gateway, lamda function, and dynamo db table necessary to store a visitor counter.

Globals: # any parameters you want available to all your resources
    Function:
      Runtime: python3.6 # language used at runtime
      Timeout: 180 # timeout for a given lambda function execution
      Environment:
          Variables: # these will be important later
              DYNAMO_TABLE: !Ref dynamodb_resume_visitors_table
              DB_ENDPOINT: http://dynamodb.us-east-1.amazonaws.com
              REGION_NAME: us-east-1

Resources:

  #Lambda Functions https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  NewVisitorFunction: # the resource’s logical name
      Type: AWS::Serverless::Function
      Properties:
          Handler: function.write_ip_datetime_handler # the path to the lambda handler code
          Policies: AmazonDynamoDBFullAccess # default IAM policy that allows the lambda to read and write to our soon to be defined Dynamo instance
          Runtime: python3.8
          CodeUri:
            ZipFile: lambda_python_functions/lambda_wite_ip.py
          Events:
              Api: # This lambda is triggered by a request to the API Gateway Endpoint /get-breed
                  Type: Api
                  Properties:
                      Path: /count_visitors
                      Method: get

  #Defines the DynamDB table that the lambda functions above are expecting:
  dynamodb_resume_visitors_table:
      Type: AWS::Serverless::SimpleTable #or AWS::DynamoDB::Table as "This property is passed directly to the TableName property of an AWS::DynamoDB::Table resource.  - This property is passed directly to the TableName property of an AWS::DynamoDB::Table resource.
      Properties:
        TableName: dynamodb_resume_visitors_table
        PrimaryKey:
            Name: ip-datetime
            Type: String
        AttributeDefinitions:
        - AttributeName: ip
          AttributeType: S
        - AttributeName: datetime
          AttributeType: S
      KeySchema:
        - AttributeName: ip
          KeyType: HASH
        - AttributeName: datetime
          KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnit: 5
            WriteCapacityUnits: 5
        Tags:
            AppType: Serverless
