name: Python CI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
        pip install pipenv
        pipenv install flake8 pytest pytest-cov boto3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 lambda_python_functions/. --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 lambda_python_functions/. --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - #name: Test with pytest
      #run: |
        #pipenv run pytest lambda_python_functions/. --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
