name: Python Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest lambda_python_functions/lambda_read.py --doctest-modules --junitxml=junit/test-results0.xml --cov=com --cov-report=xml --cov-report=html
        pytest lambda_python_functions/lambda_write.py --doctest-modules --junitxml=junit/test-results1.xml --cov=com --cov-report=xml --cov-report=html
        pytest lambda_python_functions/lambda_delete.py --doctest-modules --junitxml=junit/test-results2.xml --cov=com --cov-report=xml --cov-report=html
        pytest lambda_python_functions/lambda_update.py --doctest-modules --junitxml=junit/test-results3.xml --cov=com --cov-report=xml --cov-report=html
        pytest lambda_python_functions/lambda_list.py --doctest-modules --junitxml=junit/test-results4.xml --cov=com --cov-report=xml --cov-report=html
        pytest lambda_python_functions/clear_table.py --doctest-modules --junitxml=junit/test-results5.xml --cov=com --cov-report=xml --cov-report=html
